In [1]:
%run modules.ipynb

[[6]
 [7]] (2,)
[[2 5]] (2,)
[[12 30]
 [14 35]]
[[12 30]
 [14 35]]
[[[ 2  3]
  [ 2  3]
  [ 2  3]]

 [[ 8 10]
  [ 8 10]
  [ 8 10]]]
[[2 3]
 [2 3]
 [2 3]]
changed5


In [2]:
import mnist
X_train = mnist.train_images()[10000:,:,:].reshape(50000,1,28,28)
X_val = mnist.train_images()[:10000,:,:].reshape(10000,1,28,28)
X_test = mnist.test_images().reshape(10000,1,28,28)
y_test = mnist.test_labels()
y_train = mnist.train_labels()[10000:]
y_val = mnist.train_labels()[:10000]

In [3]:
from sklearn.preprocessing import OneHotEncoder# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
y_train = enc.fit_transform(y_train.reshape(-1, 1)).toarray()
y_val = enc.transform(y_val.reshape(-1, 1)).toarray()

In [4]:
# batch generator
def get_batches(dataset, batch_size):
    X, Y = dataset
    n_samples = X.shape[0]
        
    # Shuffle at the start of epoch
    indices = np.arange(n_samples)
    np.random.shuffle(indices)
    
    for start in range(0, n_samples, batch_size):
        end = min(start + batch_size, n_samples)
        
        batch_idx = indices[start:end]
    
        yield X[batch_idx], Y[batch_idx]

In [5]:
seq = Sequential()
seq.add(Conv2d(1, 16, 5))
seq.add(ReLU())
seq.add(MaxPool2d(2))
seq.add(Conv2d(16, 32, 5))
seq.add(ReLU())
seq.add(MaxPool2d(2))
seq.add(Flatten())
seq.add(Linear(32*7*7, 10))

In [6]:
criterion = ClassNLLCriterion()
optimizer_config = {'learning_rate' : 5e-2, 'momentum': 0.9}
loss_history = []

In [7]:
n_epoch = 15
batch_size = 1000

for i in range(n_epoch):
    for x_batch, y_batch in get_batches((X_train, y_train), batch_size):
        
        seq.zeroGradParameters()
        
        # Forward
        print('Forward')
        predictions = seq.forward(x_batch)
        loss = criterion.forward(predictions, y_batch)
    
        # Backward
        print('Backward')
        dp = criterion.backward(predictions, y_batch)
        seq.backward(x_batch, dp)
        
        
        # Update weights
        print('Updating weights')
        sgd_momentum(seq.getParameters(),  seq.getGradParameters(), optimizer_config, optimizer_state)  
        loss_history.append(loss)
        

    # Visualize
    display.clear_output(wait=True)
    plt.figure(figsize=(8, 6))
        
    plt.title("Training loss")
    plt.xlabel("#iteration")
    plt.ylabel("loss")
    plt.plot(np.log(loss_history_ReLu), label='ReLU')
    plt.plot(np.log(loss_history_LeakyReLu), label = 'LeakyReLU')
    plt.plot(np.log(loss_history_ELU), label = 'ELU')
    plt.plot(np.log(loss_history_SoftPlus), label = 'SoftPlus')
    plt.legend()
    plt.show()
    
    print('Current loss ReLU: %f' % loss)

Forward
outp_shape max (1000, 16, 14, 14)
outp_shape max (1000, 32, 7, 7)
Backward
outp_shape max (1000, 16, 14, 14)
outp_shape max (1000, 32, 7, 7)


ValueError: in1 and in2 should have the same dimensionality